### ISSUE TITLE
Add `model_path` to `init_kwargs` in `serve.yaml` as an explicit argument

### ISSUE THREAD

**Issue by outtanames** [autonomi-ai/nos#474]
Right now we require that all `__init__` functions take in a model path, and we don't require this in the `serve.yaml` spec for defining init arguments. This is a bit confusing and leads to frequent off-by-one errors, so we should just bite the bullet and require it as part of `serve.yaml` even though its used everywhere.

**Comment by spillai** [comment]
Resolved in #475
